### ISSUE TITLE
NA N firmware changelog

### ISSUE THREAD

**Issue by podwhitehawk** [drone540/mazda-firmware-changelogs#1]
hi,

could you adapt [changelog for NA N](https://mazda3revolution.com/forums/2403015-post3279.html) into yours?

**Comment by drone540** [comment]
Ok, sure. lemme just figure out what all is different besides some versions i'm missing. I've beenmeaning to go thru the thread looking for updates.

**Comment by drone540** [comment]
I have updated the long now. I have kept some of the original wording for version 59.00.544 that was previously in 59.00.545 as I thought it sounded better in the original version and provided more details. 540 I just kept the posted version since it was close enough.

**Comment by podwhitehawk** [comment]
Thanks for updating, that may be useful as a reference for any changes instead of keeping it as separate posts in 300+ forum pages.
One more known change in 70.00.021X is Pause when muted in MZD Connect.
Cheers!

**Comment by drone540** [comment]
Okay. I'll add that Pause on mute as I finally found a source to it: https://github.com/Trevelopment/MZD-AIO/issues/17

It looks like it might have been included in version 70.00.000 according to the guy who posted the feature said he was on that version and was about to upgrade to .021 after he posted that.
